# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd1966887c43b3276fd627186fa4f16d2dca87748f6c57e5fec3c507adc2852ec606d06dba2ddbb8c369c650b31209a4c8925903ba15085e367bd0666068687c

test:
  secret_key_base: 85dcc17227bdab1433c2aba46500a930a504b355f46795f2a9da899507ee3872880d9978b8aa92b112b0c21bef782379e8ba66b1bdd3253234cb93d21aef06f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
